### ISSUE TITLE
Why there is scaling factor of 0.25?

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [binli123/dsmil-wsi#11]
Hi,

Thanks for sharing your work. I have read the paper and understand you are grabbing tiles at lower mag (Single Tile( and concatenating/adding with corresponding (16 Tiles) at 20x. 
What I don't understand is the reason behind choosing 0.25. Can you please elaborate. 
https://github.com/binli123/dsmil-wsi/blob/c3b550d1ed61273c1a7c8032410e2abdfa47a871/compute_feats.py#L103

Thank you.

**Comment by binli123** [comment]
It is chosen arbitrarily, The purpose of addition is to resemble the **Positional Encoding** in [transformers](https://arxiv.org/abs/1706.03762). You could treat this as a spatial encoding mechanism. Ideally, this number should be a learned scalar. The other option is to use direct concatenation.
