### ISSUE TITLE
Generating embeddings for Camelyon16

### ISSUE THREAD

**Issue by gokberkgul** [binli123/dsmil-wsi#18]
First of all, thank you for the great work.

I am trying to train with your DSMIL model, but I have a different backbone that generates the embeddings, I would like to just train the MIL part. My question is, while you were generating the csv files, have you applied transformation to the patch images (other than `toTensor()`), or just fed the images to the already trained Resnet18 backbone? I will also generate the csv files like your work, but I would like to hear your recommendation before doing so.

**Comment by binli123** [comment]
The embeddings were computed without transformation on the original patches.   
If your bandwidth permits, you can precompute multiple embeddings of a patch with different random transformations, and during the training of the MIL model, randomly pick one of these to form the bag.
