### ISSUE TITLE
Discarding background patches

### ISSUE THREAD

**Issue by qkrtnskfk23** [binli123/dsmil-wsi#20]
Hello.

Your work is very nice and so I'm trying to reproduce your result on camelyon 16.

From WSIs (tif) of camelyon 16, I'm cropping the patches, but the number of patches (about 10000 patches in a bag) is slightly larger than reported number of patches in your paper(about 8000 patches in a bag). 

In a paper, I read that you discarded the background patches (entropy < 5).

Is part of discarding patches included in  your code? If so, where can i find that part?

Or What method did you use for discarding patches based on the entropy?

Thank you for your great work.

**Comment by Dylan-H-Wang** [comment]
> Please check the following code snippet, the actual implementation uses the sum of edges (after applying an edge detection filter)
> 
> https://github.com/binli123/dsmil-wsi/blob/f304bedbff7d275e052d9bae8e1e56c759f6e2cc/deepzoom_tiler.py#L69-L76
> 
> 
> You can adjust the threshold by passing the argument `--background_t` to `deepzoom_tiler.py`.

May I ask whether the threshold you set, i.e., 0.25, is universal for all datasets, or it is just suitable for your experiment two datasets (TCGA and Camelyon16).
Thank you!

**Comment by binli123** [comment]
> > Please check the following code snippet, the actual implementation uses the sum of edges (after applying an edge detection filter)
> > https://github.com/binli123/dsmil-wsi/blob/f304bedbff7d275e052d9bae8e1e56c759f6e2cc/deepzoom_tiler.py#L69-L76
> > 
> > You can adjust the threshold by passing the argument `--background_t` to `deepzoom_tiler.py`.
> 
> May I ask whether the threshold you set, i.e., 0.25, is universal for all datasets, or is it just suitable for your experiment two datasets (TCGA and Camelyon16)? Thank you!

Normally 15-30 (for 8-bit images) would work for most of the datasets, You could also tweak that value and check the results to see if that gets rid of the background patches.

**Comment by saarthak02** [comment]
Hi Bin,

Thanks a lot for your active responses so far. I am using TGCA-Lung cancer dataset, with exact save SVS files as yours. But even with threshold like 30, my number of images at 5X are coming around 0.8 million, whereas yours were 0.36 million patches at 5× as you mentioned in the paper. Can you please guide me where I am doing wrong? Did you used higher threshold for Lung cancer dataset or did you used any additional filtering criteria?
