### ISSUE TITLE
Pre-trained Weights

### ISSUE THREAD

**Issue by GeorgeBatch** [binli123/dsmil-wsi#21]
Hi Bin Li,

Thank you very much for such a thorough explanation of how everything works in the README! Also, thank you for making so many things public (representations, weights, and even some of the data).

Could you please explain which of the weights in the [TCGA folder](https://drive.google.com/drive/folders/1Rn_VpgM82VEfnjiVjDbObbBFHvs0V1OE) corresponds to which magnification? As I understand, one should be for the 5x and the other for the 20x magnification embedder network, but I do not understand which one is which.

Many thanks,
George

**Comment by binli123** [comment]
Those are all for high-mag. I uploaded low-mag weights to the same folder.
