### ISSUE TITLE
About the csv file

### ISSUE THREAD

**Issue by ZechengLi19** [binli123/dsmil-wsi#24]
simclr/all_patches.csv
How to generate the csv file?
And what kind of data is stored in it?

**Comment by lzcqk** [comment]
thanks！

**Comment by binli123** [comment]
In `simclr/run.py`:
https://github.com/binli123/dsmil-wsi/blob/e637f8295e0bc580e20569586b11ce69a75190c6/simclr/run.py#L8-L19

Basically, these are paths to all the patches.

**Comment by lzcqk** [comment]
Thank you so much！！
