### ISSUE TITLE
Request for patch-level labels of CAMELYON 16

### ISSUE THREAD

**Issue by XiaoyuanL73** [binli123/dsmil-wsi#31]
Thanks for your brilliant work and sharing the precomputed features of CAMELYON 16! 
But only slide-level labels are available in the precomputed features. Could you please further release the patch-level labels of the precomputed features?

**Comment by binli123** [comment]
The training pipeline for patch-based training is almost entirely different and I currently don't have feature-label pairs saved. I only group positive patches and negative patches into separate folders and follow a standard way of training a resnet. The annotations can be found here: https://camelyon16.grand-challenge.org/Data/, following the `download` links in camelyon17'page and pick `data->camelyon16 dataset`. The patch names are essentially coordinates (need to be multiplied by the patch size) and it is easy to judge if a patch falls into an annotation or not by reading the polygons from the annotation xml.

**Comment by XiaoyuanL73** [comment]
Thank you for your prompt reply!

**Comment by saurabhmishra608** [comment]
is the patch level labels available for the TCGA dataset?
