### ISSUE TITLE
Camelyon16: pretrained embedders

### ISSUE THREAD

**Issue by Bontempogianpaolo1** [binli123/dsmil-wsi#40]
Hi @binli123,
Given the data obtained as #39, I extracted the features using both model-v0 and model-v2. The differences between their performances on the downstream task are evident. Here is the AUC: 
<img width="203" alt="image" src="https://user-images.githubusercontent.com/28188499/170201649-fcbbdd58-f205-49c5-ac50-5d282ae0fe9a.png">

Looking at #12 you say they differ for batch size and training time. Could you be more specific?

**Comment by binli123** [comment]
In my case both are converging, v2 converges significantly slower at around 100 epoch. If you load "init.pth" it would be much faster.

**Comment by binli123** [comment]
I incorporated a simple weights initialization method which helps stabilize the training in the latest commit.
