### ISSUE TITLE
how to set postive instance or negative class?

### ISSUE THREAD

**Issue by dawalisi** [binli123/dsmil-wsi#47]
because there is a MIL task,  the setting of positivte class is important

**Comment by jjjharden** [comment]
Hellow，I am studying DSMIL recently, can we discuss some problems together?

**Comment by dawalisi** [comment]
> Hellow，I am studying DSMIL recently, can we discuss some problems together?

YES

**Comment by jjjharden** [comment]
你是中国人吗？是的话可以加个联系方式，方便沟通


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binli123/dsmil-wsi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月13日(星期三) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binli123/dsmil-wsi] how to set postive instance or negative class? (Issue #47)





  
Hellow，I am studying DSMIL recently, can we discuss some problems together?
  
YES

**Comment by dawalisi** [comment]
> > > Hellow，I am studying DSMIL recently, can we discuss some problems together?
> > 
> > 
> > YES
> 
> Are you Chinese? We can add contact information to facilitate communication.



> > > Hellow，I am studying DSMIL recently, can we discuss some problems together?
> > 
> > 
> > YES
> 
> Are you Chinese? We can add contact information to facilitate communication.

是的，你要加什么QQ还是微信呀？

**Comment by jjjharden** [comment]
QQ吧






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月14日(星期四) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binli123/dsmil-wsi] how to set postive instance or negative class? (Issue #47)





    
Hellow，I am studying DSMIL recently, can we discuss some problems together?
  
YES
  
Are you Chinese? We can add contact information to facilitate communication.
     
Hellow，I am studying DSMIL recently, can we discuss some problems together?
  
YES
  
Are you Chinese? We can add contact information to facilitate communication.
  
是的，你要加什么QQ还是微信呀？

**Comment by dawalisi** [comment]
> QQ吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月14日(星期四) 上午9:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [binli123/dsmil-wsi] how to set postive instance or negative class? (Issue #47) Hellow，I am studying DSMIL recently, can we discuss some problems together? YES Are you Chinese? We can add contact information to facilitate communication. Hellow，I am studying DSMIL recently, can we discuss some problems together? YES Are you Chinese? We can add contact information to facilitate communication. 是的，你要加什么QQ还是微信呀？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;



> QQ吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月14日(星期四) 上午9:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [binli123/dsmil-wsi] how to set postive instance or negative class? (Issue #47) Hellow，I am studying DSMIL recently, can we discuss some problems together? YES Are you Chinese? We can add contact information to facilitate communication. Hellow，I am studying DSMIL recently, can we discuss some problems together? YES Are you Chinese? We can add contact information to facilitate communication. 是的，你要加什么QQ还是微信呀？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

2873596282
