### ISSUE TITLE
Pre-computed features of Camelyon16 datasets

### ISSUE THREAD

**Issue by 86ai68** [binli123/dsmil-wsi#50]
Thank you very much for the Pre-computed features of Camelyon16 datasets provided in your code(https://uwmadison.box.com/shared/static/l9ou15iwup73ivdjq0bc61wcg5ae8dwe.zip). What I would like to ask you is on which WSI  magnification scale is this feature extracted? Is it only 20X or 20X and 5X concatenated together? I look forward to hearing from you very much. Thanks!

**Comment by binli123** [comment]
These are 20x features.

**Comment by 86ai68** [comment]
The questions have been solved
