### ISSUE TITLE
What is aggregator.pth?

### ISSUE THREAD

**Issue by jianan-zhang** [binli123/dsmil-wsi#51]
Thanks for sharing this amazing work. I wonder what is the 'aggregator.pth' for the dsmil model. Is it trained on some specific dataset? How can I get it on my own dataset? Looking forward to your reply. 

Best Wishes!

**Comment by binli123** [comment]
The ‘aggregator.pth' is the provided pretrained weights for the dsmil model for testing. If you trained your own model, your weights will be saved in the folder 'weights/{date}/*.pth'. You can then load it for testing.

**Comment by jianan-zhang** [comment]
Thank you so much.
