### ISSUE TITLE
Wondering the TCGA test data label

### ISSUE THREAD

**Issue by XiaoXueShengwangrui** [binli123/dsmil-wsi#56]
[Example img in your Repo ](https://github.com/binli123/dsmil-wsi/blob/master/thumbnails/bags.png)
![image](https://user-images.githubusercontent.com/32757858/192757145-444618b9-93c3-4aec-8c48-704b0278c2c5.png)

In this image has shown the line 3 about slide of case  **TCGA-64-5778-01Z** , which label is 0 (negative bag= normal case).
However, in the GDC data portal, the sample type has shown is [**Primary Tumor** ](https://portal.gdc.cancer.gov/cases/8fdbd88f-19ae-4ab8-bcd7-6bfa1bbde742?bioId=15e53529-1ff6-49f2-865e-cc43d83d3139#:~:text=Sample%20Type-,Primary%20Tumor,-Sample%20Type%20Id).
![image](https://user-images.githubusercontent.com/32757858/192757361-90952d07-2076-4c98-8a96-f31cd8ccb974.png)

So, is there any mistake I understand?
Look forward to your reply!

**Comment by binli123** [comment]
Yes, there is. This dataset contains two subtypes of tumors. 0 is tumor type 0, and 1 is tumor type 1. They are both tumors. Please check the readme -> Feature vector csv files explanation -> 3.Labels.

**Comment by binli123** [comment]
3. Labels.
> For binary classifier, use `1` for positive bags and `0` for negative bags. Use `--num_classes=1` at training.  
> For multi-class classifier (`N` positive classes and one optional negative class), use `0~(N-1)` for positive classes. If you have a negative class (not belonging to any one of the positive classes), use `N` for its label. Use `--num_classes=N` (`N` equals the number of **positive classes**) at training.

**Comment by XiaoXueShengwangrui** [comment]
Ok, got it, thank u very much !
