### ISSUE TITLE
Why some slides are corrupted? 

### ISSUE THREAD

**Issue by wwyi1828** [binli123/dsmil-wsi#62]
Thank you for your excellent work!

You mentioned in the paper that four low-quality corrupted slides are discarded, but the Google Drive link provided by this repository contains 11 excluded slides. Also, I took a glance at the thumbnail images of the 11 excluded slides. They don't appear to be very different from other slides.

Could you clarify why the 11 slides were excluded, and what the difference is between the 4 excluded slides in paper that and the 11 exclude slides in this repository? Thank you so much!

**Comment by binli123** [comment]
Maybe you should check the images, not the thumbnails. I remember those are very old slides with quality issues.

**Comment by wwyi1828** [comment]
> Maybe you should check the images, not the thumbnails. I remember those are very old slides with quality issues.

Thanks for your reply! You're right. There are 10 slides that don't have the original magnification level information in the dataset, and the excluded 11 slides include these 10 slides. Despite the high resolution rate, the rest one excluded slide, is blurry.
