### ISSUE TITLE
Camelyon16 Patching

### ISSUE THREAD

**Issue by bryanwong17** [binli123/dsmil-wsi#63]
Could you please let me know how to patch the camelyon16 dataset with the same settings as yours (5x and 20x)? Thanks

**Comment by bryanwong17** [comment]
Below is what I got from using python deepzoom_tiler.py -m 1 -b 20 -d Camelyon16 -v tif

Do you add some filtering patches?

![image](https://user-images.githubusercontent.com/67773304/209246397-c5f80270-4d33-4232-b49d-b1c7c2c99425.png)

**Comment by binli123** [comment]
Threshold for filtering out background is set in
https://github.com/binli123/dsmil-wsi/blob/dbb5cab415fb4079f89d8c977c34efd533ee87fa/deepzoom_tiler.py#L255
