### ISSUE TITLE
Precomputed features

### ISSUE THREAD

**Issue by gadermayr** [binli123/dsmil-wsi#72]
I have a question regarding the precomputed features (Camelion/TCGA) which can be downloaded (e.g.  $ python download.py --dataset=tcga).

Where these features generated with a ResNet trained on image-net, or based on self supervised training (simclr)? Are the features for the other case also available in the precomputed form?

Thank you very much!

**Comment by binli123** [comment]
Those are based on self-supervised training.

**Comment by gadermayr** [comment]
Thank you very much for the information!

**Comment by jan-engelmann** [comment]
thank you!
And are these features multi scale or single scale for Camelion?

**Comment by jan-engelmann** [comment]
found the answer here:
https://github.com/binli123/dsmil-wsi/issues/50
