### ISSUE TITLE
Question about some model architecture 

### ISSUE THREAD

**Issue by aw200897** [binli123/dsmil-wsi#8]
Hi, I have some questions about MIL Aggregator.

In your paper, you used a dual-stream aggregator. Finally, you combine Cm and Cb, but I do not find cm operation in  dsml.py.
Excuse me, what part of the program about Cm operation.

**Comment by binli123** [comment]
>  line 68-69:
        feats, classes = self.i_classifier(x)
        prediction_bag, A, B = self.b_classifier(feats, classes)

This produces instance scores in the variable "classes", and are passed to self.b_classifier.

> Line 45-47: 
            _, indices = torch.sort(c[:, i], 0, True)         
            feats = torch.index_select(feats, 0, indices) # N x K, sorted
            q_max = self.q(feats[0].view(1, -1)) # 1 x 1 x Q

Sort the embeddings according to the instance scores in descending order and take the first embedding (the one with the maximum score), compute the query of this embedding. The query is then used for computing distances to other embeddings.
